export const paymentRecords: PaymentRecord[] = [
  {
    name: "Laptop",
    img: "laptop.jpg",
    price: "$1200",
    transactionNumber: "123456",
    transactionTime: "12:30",
    status: "Settled",
  },
  {
    name: "Smartphone",
    img: "smartphone.png",
    price: "$800",
    transactionNumber: "789012",
    transactionTime: "14:45",
    status: "Un-reconciled",
  },
  {
    name: "Camera",
    img: "camera.jpg",
    price: "$500",
    transactionNumber: "345678",
    transactionTime: "10:15",
    status: "Pending",
  },
  {
    name: "Headphones",
    img: "headphones.jpg",
    price: "$150",
    transactionNumber: "901234",
    transactionTime: "16:20",
    status: "Reconciled",
  },
  {
    name: "Coffee Maker",
    img: "coffee_maker.jpg",
    price: "$100",
    transactionNumber: "567890",
    transactionTime: "13:00",
    status: "Unsettled",
  },
  {
    name: "Fitness Tracker",
    img: "fitness_tracker.jpg",
    price: "$80",
    transactionNumber: "234567",
    transactionTime: "09:45",
    status: "Reconciled",
  },
  {
    name: "Desk Chair",
    img: "desk_chair.jpg",
    price: "$200",
    transactionNumber: "890123",
    transactionTime: "15:30",
    status: "Settled",
  },
  {
    name: "Portable Speaker",
    img: "portable_speaker.jpg",
    price: "$50",
    transactionNumber: "456789",
    transactionTime: "11:00",
    status: "Un-reconciled",
  },
  {
    name: "Blender",
    img: "blender.jpg",
    price: "$60",
    transactionNumber: "012345",
    transactionTime: "14:00",
    status: "Pending",
  },
  {
    name: "External Hard Drive",
    img: "external_hard_drive.jpg",
    price: "$90",
    transactionNumber: "678901",
    transactionTime: "08:30",
    status: "Reconciled",
  },
  {
    name: "Wireless Mouse",
    img: "wireless_mouse.jpg",
    price: "$25",
    transactionNumber: "123456",
    transactionTime: "12:30",
    status: "Settled",
  },
  {
    name: "Television",
    img: "television.jpg",
    price: "$1000",
    transactionNumber: "789012",
    transactionTime: "14:45",
    status: "Un-reconciled",
  },
  {
    name: "Backpack",
    img: "backpack.jpg",
    price: "$40",
    transactionNumber: "345678",
    transactionTime: "10:15",
    status: "Pending",
  },
  {
    name: "Gaming Console",
    img: "gaming_console.jpg",
    price: "$300",
    transactionNumber: "901234",
    transactionTime: "16:20",
    status: "Reconciled",
  },
  {
    name: "Kitchen Mixer",
    img: "kitchen_mixer.jpg",
    price: "$120",
    transactionNumber: "567890",
    transactionTime: "13:00",
    status: "Unsettled",
  },
  {
    name: "E-book Reader",
    img: "ebook_reader.jpg",
    price: "$150",
    transactionNumber: "234567",
    transactionTime: "09:45",
    status: "Reconciled",
  },
  {
    name: "Smartwatch",
    img: "smartwatch.jpg",
    price: "$180",
    transactionNumber: "890123",
    transactionTime: "15:30",
    status: "Settled",
  },
  {
    name: "Desk Lamp",
    img: "desk_lamp.jpg",
    price: "$30",
    transactionNumber: "456789",
    transactionTime: "11:00",
    status: "Un-reconciled",
  },
  {
    name: "Printed Books",
    img: "printed_books.jpg",
    price: "$70",
    transactionNumber: "012345",
    transactionTime: "14:00",
    status: "Pending",
  },
  {
    name: "Digital Camera",
    img: "digital_camera.jpg",
    price: "$250",
    transactionNumber: "678901",
    transactionTime: "08:30",
    status: "Reconciled",
  },
  {
    name: "Wireless Earbuds",
    img: "wireless_earbuds.jpg",
    price: "$80",
    transactionNumber: "123456",
    transactionTime: "12:30",
    status: "Settled",
  },
  {
    name: "Sofa",
    img: "sofa.jpg",
    price: "$700",
    transactionNumber: "789012",
    transactionTime: "14:45",
    status: "Un-reconciled",
  },
  {
    name: "Air Purifier",
    img: "air_purifier.jpg",
    price: "$120",
    transactionNumber: "345678",
    transactionTime: "10:15",
    status: "Pending",
  },
  {
    name: "Microwave Oven",
    img: "microwave_oven.jpg",
    price: "$80",
    transactionNumber: "901234",
    transactionTime: "16:20",
    status: "Reconciled",
  },
  {
    name: "Digital Clock",
    img: "digital_clock.jpg",
    price: "$15",
    transactionNumber: "567890",
    transactionTime: "13:00",
    status: "Unsettled",
  },
  {
    name: "Office Desk",
    img: "office_desk.jpg",
    price: "$180",
    transactionNumber: "234567",
    transactionTime: "09:45",
    status: "Reconciled",
  },
  {
    name: "Wireless Keyboard",
    img: "wireless_keyboard.jpg",
    price: "$50",
    transactionNumber: "890123",
    transactionTime: "15:30",
    status: "Settled",
  },
  {
    name: "Dumbbells Set",
    img: "dumbbells_set.jpg",
    price: "$90",
    transactionNumber: "456789",
    transactionTime: "11:00",
    status: "Un-reconciled",
  },
  {
    name: "Vacuum Cleaner",
    img: "vacuum_cleaner.jpg",
    price: "$120",
    transactionNumber: "012345",
    transactionTime: "14:00",
    status: "Pending",
  },
  {
    name: "Smart Thermostat",
    img: "smart_thermostat.jpg",
    price: "$60",
    transactionNumber: "678901",
    transactionTime: "08:30",
    status: "Reconciled",
  },
];

export const getPaymentRecords = (): PaymentRecord[] => paymentRecords;
